source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'sass'
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'
gem 'bcrypt-ruby', '~> 3.0.0', :require => "bcrypt"
gem 'warden'
gem 'sinatra-flash'
gem 'recaptcha'
gem 'pony'
gem 'sinatra-contrib'
